apiVersion: v1
kind: Service
metadata:
  name: standings
  labels:
    app: standings
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: standings
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: standings
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: standings
    spec:
      containers:
      - name: standings
        image: sevteen/notact-standings:0.1.0-bug
        ports:
        - containerPort: 8080
        env:
          - name: APPLICATION_ID
            value: standings
          - name: BROKER_ADDRESS
            value: tcp://${ACTIVEMQ_SERVICE_HOST}:${ACTIVEMQ_SERVICE_PORT}
          - name: TOPIC_STARTED
            value: started
          - name: TOPIC_COMPLETED
            value: completed
          - name: SPRING_PROFILES_ACTIVE
            value: activemq
        readinessProbe:
           tcpSocket:
              port: 8080
           periodSeconds: 3
